/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary:       '#3D1225',
          'primary-hover': '#5C2040',
          copper:        '#C49A6C',
          'copper-light': '#E8D5B7',
          'copper-dark':  '#A07845',
          bg:            '#FAF6F1',
          surface:       '#F5EFE9',
          blush:         '#F5E0E8',
          muted:         '#8C7378',
          cream:         '#FAF6F1',
          sand:          '#EFE3D8',
        },
        masc: {
          dark:          '#0F0E0D',
          darker:        '#070605',
          surface:       '#1A1714',
          surface2:      '#221E1B',
          copper:        '#C49A6C',
          'copper-light': '#E8D5B7',
          'copper-dark':  '#A07845',
          warm:          '#E8E0D8',
          muted:         '#6B6258',
          stone:         '#44403C',
          'stone-light': '#78716C',
          gold:          '#C49A6C',
          'gold-light':  '#E8D5B7',
          'gold-dim':    '#A07845',
          smoke:         '#57534E',
        },
      },
      fontFamily: {
        sans:         ['Montserrat', 'system-ui', 'sans-serif'],
        display:      ['Cormorant Garamond', 'Georgia', 'serif'],
        'fem-display': ['Cormorant Garamond', 'Georgia', 'serif'],
        'masc-display': ['Cormorant Garamond', 'Georgia', 'serif'],
        'masc-body':  ['Montserrat', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in':     'fadeIn 0.4s ease-out',
        'slide-up':    'slideUp 0.35s ease-out',
        'smoke-drift': 'smokeDrift 8s ease-in-out infinite',
        'smoke-drift2': 'smokeDrift2 11s ease-in-out infinite',
        'copper-glow': 'copperGlow 3s ease-in-out infinite',
        'gold-glow':   'copperGlow 3s ease-in-out infinite',
        'ember-float': 'emberFloat 6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:   { from: { transform: 'translateY(20px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        smokeDrift: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)', opacity: '0.3' },
          '33%':      { transform: 'translate(30px, -20px) scale(1.15)', opacity: '0.5' },
          '66%':      { transform: 'translate(-20px, 15px) scale(0.9)', opacity: '0.25' },
        },
        smokeDrift2: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)', opacity: '0.2' },
          '40%':      { transform: 'translate(-35px, 25px) scale(1.2)', opacity: '0.4' },
          '70%':      { transform: 'translate(25px, -18px) scale(0.85)', opacity: '0.15' },
        },
        copperGlow: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(196,154,108,0.3)' },
          '50%':      { boxShadow: '0 0 30px rgba(196,154,108,0.6)' },
        },
        emberFloat: {
          '0%, 100%': { transform: 'translateY(0) scale(1)', opacity: '0.7' },
          '50%':      { transform: 'translateY(-20px) scale(0.8)', opacity: '0.3' },
        },
      },
      boxShadow: {
        'card':       '0 2px 12px rgba(61,18,37,0.06)',
        'card-hover': '0 12px 40px rgba(61,18,37,0.12)',
        'copper':     '0 4px 20px rgba(196,154,108,0.30)',
        'copper-lg':  '0 8px 32px rgba(196,154,108,0.40)',
        'burgundy':   '0 4px 20px rgba(61,18,37,0.25)',
        'rose':       '0 4px 20px rgba(196,154,108,0.28)',
        'gold':       '0 4px 20px rgba(196,154,108,0.30)',
        'gold-lg':    '0 8px 32px rgba(196,154,108,0.40)',
        'masc-card':  '0 2px 16px rgba(0,0,0,0.4)',
        'masc-hover': '0 8px 40px rgba(0,0,0,0.6)',
      },
      backdropBlur: { xs: '2px' },
    },
  },
  plugins: [],
};
